blank_issues_enabled: false
contact_links:
  - name: Bug Report
    url: https://github.com/SirEndii/AdvancedPeripherals/issues/new/choose
    about: Please report bugs there.
  - name: Documentation Issues
    url: https://github.com/Seniorendi/Advanced-Peripherals-Documentation/issues
    about: Please create issues of the documentation at the proper repository.
